# Generated by Django 4.2.5 on 2023-09-19 16:40

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.image_upload_path),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
