# Generated by Django 4.2.5 on 2023-09-21 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_post_header_image_delete_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-updated_on']},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
