# Generated by Django 4.2.5 on 2023-09-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippets',
            field=models.CharField(default='Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eius distinctio rem dolores, eligendi necessitatibus, iusto voluptatibus sint sed delectus provident aperiam porro deserunt quibusdam! Dolorum nihil recusandae id veritatis vitae, odio dicta sed iure at optio iusto magnam saepe nesciunt eveniet aperiam, ut enim numquam rerum hic ipsam quam! Quae voluptatum expedita soluta consequuntur omnis ratione quo pariatur, at, quam consequatur impedit blanditiis rerum, amet cumque quos suscipit sapiente est ea delectus maiores nemo nisi non libero corporis. Voluptatibus veritatis est, rerum accusantium vero similique! Veritatis amet laborum at ea fugiat accusantium molestiae labore repudiandae quaerat minus! Corrupti, deserunt harum? Ipsam aliquam eligendi, odio dignissimos voluptatum molestias, minus quibusdam ut reiciendis at atque eius sed pariatur sequi magni corporis, rem culpa. Corporis obcaecati dolores iste consequatur possimus, hic velit explicabo placeat! Veniam blanditiis eius ducimus, maxime reprehenderit repellendus inventore vel consequuntur eligendi rerum libero! A dolore sint, accusantium nostrum aliquam soluta ea quas deserunt nemo nihil consectetur asperiores fuga reprehenderit, dolorum fugiat blanditiis iure! Sapiente laboriosam laborum amet iste, explicabo accusantium illo enim quibusdam nostrum debitis hic soluta facere suscipit provident incidunt sunt tenetur id nisi impedit deserunt nam at ducimus perferendis assumenda. Enim blanditiis esse sequi at facere commodi?', max_length=255),
        ),
    ]
